### ISSUE TITLE
Unable to load ini file.

### ISSUE THREAD

**Issue by Ndawen** [tetele/superslicer-profiles#8]
When I move the blv.ini file into the directory superslicer will not run gives an error code.

**Comment by tetele** [comment]
Can you please provide the error code, along with the version of SuperSlicer that you are using?

**Comment by Ndawen** [comment]
version 2.3.56.9
Failed loading config bundle "C:\Users\David\AppData\Roaming\SuperSlicer\vendor\BLV.ini"
Error: "'=' character not found in line" at line 7

**Comment by tetele** [comment]
Have you edited the `BLV.ini` file in any way? [Line 7](https://github.com/tetele/superslicer-profiles/blob/master/BLV.ini#L7) should be empty and I cannot reproduce the issue on my machine with the same SS version.

**Comment by Ndawen** [comment]
No sir no editing. What should line 7 say ?

**Comment by Ndawen** [comment]
I’ll download the file again somehow it’s became corrupted.

**Comment by tetele** [comment]
Any news here @Ndawen? Can I close the issue?

**Comment by Ndawen** [comment]
Sorry I got busy printing. Yes it works now . Thank you so much for the profile.
